### ISSUE TITLE
the GUI is still visible when the F1 key is pressed

### ISSUE THREAD

**Issue by Lolothepro** [wendall911/SimpleTextOverlay#18]

**Comment by wendall911** [comment]
As many bug reports as you file ... and it is a lot. You'd think you would know by now that it is required to put some basic information in the bug report. Like which minecraft version, etc. Please do this in the future. I don't want to force templates because people are being lazy. 

Look, if you take the time, and it looks like you do take an excessive amount of time. Please always include information in bug reports. Otherwise, it just ends up spamming developers that mainly donate their time. While I appreciate the report, the quality is poor at best.

**Comment by Lolothepro** [comment]
I use NeoForge 21.0.40-beta, but in any case, I don't know what more information to give, the title explains the bug, if you want I can give a video
[SimpleTextOverlay](https://modrinth.com/mod/aY8vAgyv) : 5.2.1.7


https://github.com/wendall911/SimpleTextOverlay/assets/68275908/31b8b305-c509-4179-85bd-cb732a0f39ea

**Comment by wendall911** [comment]
Ok, that's very useful, much appreciated. Always, include the Minecraft version and modloader. No matter what project you are reporting. This mod has been around since 1.15, so there are a lot of versions floating around.

I'll have a fix out for this and the other report soon.

**Comment by wendall911** [comment]
Released on curseforge and modrinth. Give a few minutes and the new versions should be approved.
