### ISSUE TITLE
Text overlay often not visible

### ISSUE THREAD

**Issue by Nevrai** [wendall911/SimpleTextOverlay#8]
The text overlay (including the compass, if it’s enabled) frequently disappears on its own and doesn’t come back, even if I restart the game. It seems like it’ll eventually come back, seemingly randomly. I don’t know what could be causing this. This happens even when I’ve made no changes to any configs or mods. Regardless of what I try to change in the mod’s config, nothing happens. I thought there may be a toggle for the overlay, but there’s no key bind in the key binds settings.

#### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/) (version [0.4.25](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/3919940)—latest) (+ [these client-side mods](https://pastebin.com/raw/bzi3s6gW))
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Simple Text Overlay:** 3.4.0.0 (latest for 1.18.2)

**Comment by wendall911** [comment]
Ok, I think this is a conflict with another mod. Thanks for the information. I'll try to figure out what is conflicting.

**Comment by wendall911** [comment]
I've loaded the pack and it works fine with the defaults. Is there a custom configuration you're using for SimpleTextOverlay, or are you just using the defaults? I'll continue to see if I can reproduce, but without any information on what actions are being taken I can't really troubleshoot. It is probably one of the other HUD related mods causing issues.

Just to be honest, this mod does the most straight forward HUD rendering using default Forge methods. All conflicts I've seen are where other mods do very bad things like overwriting other mod hud elements. I'll add a couple that might be the issue, but honestly with a 5 minute launch time, I wouldn't expect much on my end. You'll likely need to do a binary search of what mod is causing the issue. I can guarantee it is a bug in the other mod overwriting HUD elements, or drawing things in an improper way.

I *may* be able to prevent this, but generally the fix is to either not use the other mod, or ask them to fix the bad code. (I think some of this is just leftover cruft from 1.15 and earlier in those mods implementation). Thankfully this is addressed in 1.19, so these issues should be less prevalent.

Side note: What's crazy is that I fail to see the appeal of these "all the mods" packs. It is just incredibly dumb IMO and fraught with issues. I have a POWERFUL workstation and it takes several minutes to launch. Probably a full minute or more for worldgen. Expecting to not have bugs, especially given the fact that half of these are closed-source mods that are nearly impossible to debug or give feedback on.

**Comment by wendall911** [comment]
Ok, I added:
Just Zoom (+ Konkrete)
Improved Mount HUD
Armor Status HUD Renewed (+ BobLib)

I'm still not seeing any issues. If you can do some binary search, maybe you can find the issue. I'll leave this open, but am not seeing the issue.

I'll continue to investigate.
